<template>
  <main class="site content-page pricing-page" id="site" tabindex="-1">
    <div class="wrap"><SiteNav /><section class="content-hero" aria-labelledby="pricing-title"><div><div class="eyebrow">报价说明 · 服务范围 · 付款节点</div><h1 id="pricing-title">先确认范围，再确定报价与交付。</h1><p class="content-lead">支持固定报价、分阶段报价和按工时评估。确认功能范围、需要开发的平台、接口和交付要求后，提供明确报价与排期。</p><div class="hero-actions"><RouterLink class="btn primary" to="/contact">提交项目资料，获取报价评估</RouterLink><RouterLink class="btn secondary" to="/services">查看服务范围</RouterLink></div></div><div class="hero-summary"><span>报价原则</span><strong>范围透明 · 节点清楚 · 变更可追踪</strong><p>报价以确认的功能范围和交付要求为准。</p><div class="summary-line"><b>报价模式</b><span>固定报价 / 分阶段 / 按工时</span></div><div class="summary-line"><b>售后支持</b><span>按报价单与合同约定</span></div></div></section></div>

    <section class="section pricing-flow-section" aria-labelledby="flow-title"><div class="wrap"><div class="section-head"><h2 id="flow-title" class="section-title">报价从需求确认开始</h2><p class="section-subtitle">把关键信息准备好，我会先确认范围，再给出报价方式和排期。</p></div><div class="pricing-flow-grid"><article class="pricing-flow-card"><span>01</span><h3>提交项目资料</h3><p>业务类型、核心功能、需要开发的平台和预计上线时间。</p></article><article class="pricing-flow-card"><span>02</span><h3>确认交付范围</h3><p>梳理页面、流程、角色、接口和首期完整业务流程。</p></article><article class="pricing-flow-card"><span>03</span><h3>输出报价排期</h3><p>根据范围确定报价方式、阶段节点和阶段成果。</p></article><article class="pricing-flow-card"><span>04</span><h3>签约启动项目</h3><p>确认报价单或合同后，按约定节点进入项目交付。</p></article></div></div></section>

    <section class="section pricing-packages-section" aria-labelledby="package-title"><div class="wrap"><div class="section-head"><h2 id="package-title" class="section-title">服务类型与报价方式</h2><p class="section-subtitle">根据项目阶段，选择需求评估、系统开发或持续迭代服务。</p></div><div class="pricing-grid"><article class="pricing-card"><span class="pricing-label">方案 A · 评估</span><h3>需求梳理包</h3><div class="pricing-price">￥2,000 起</div><p>适合还没有完整需求文档，需要先把业务范围和首期功能拆清楚的项目。</p><ul class="check-list"><li>业务目标、用户角色和核心流程</li><li>页面、字段、权限和接口清单</li><li>首期开发范围、报价与排期建议</li></ul></article><article class="pricing-card featured"><span class="pricing-label">方案 B · 开发</span><h3>核心系统包</h3><div class="pricing-price">按范围报价</div><p>适合先上线一条完整交易或管理流程，再按模块继续迭代的项目。</p><ul class="check-list"><li>前台、后台、接口和数据库</li><li>按阶段提供版本并确认</li><li>上线资料和基础使用说明</li></ul></article><article class="pricing-card"><span class="pricing-label">方案 C · 持续</span><h3>维护迭代包</h3><div class="pricing-price">按工时 / 阶段报价</div><p>适合已有系统，需要问题修复、版本发布、报表优化或持续增加业务模块。</p><ul class="check-list"><li>问题修复、版本发布和报表优化</li><li>新功能与原有问题分开评估</li><li>响应方式和维护范围按项目确认</li></ul></article></div></div></section>

    <section class="section soft-section" aria-labelledby="included-title"><div class="wrap"><div class="section-head"><h2 id="included-title" class="section-title">报价包含什么，不包含什么</h2><p class="section-subtitle">最终交付范围、第三方费用和维护规则，以报价单与合同约定为准。</p></div><div class="comparison-grid"><article class="comparison-card"><div class="eyebrow">通常包含</div><ul class="check-list"><li>需求范围、页面清单和首期交付边界。</li><li>约定端的页面、接口和后台模块。</li><li>阶段演示、测试修复和上线资料。</li><li>源代码、设计稿和账号，按报价单或合同约定交付。</li></ul></article><article class="comparison-card warning-panel"><div class="eyebrow">需要单独计费 / 确认</div><ul class="check-list"><li>服务器、域名、短信、支付、地图和第三方平台费用。</li><li>数据清洗、历史数据迁移和大量内容录入。</li><li>超出首期范围的功能、重大流程变更和额外端适配。</li><li>上线后的维护支持与持续迭代，按报价单或合同约定执行。</li></ul></article></div></div></section>

    <section class="section" aria-labelledby="payment-title"><div class="wrap"><div class="section-head"><h2 id="payment-title" class="section-title">付款、验收与售后节点</h2><p class="section-subtitle">默认按立项、阶段交付、最终验收分期支付，具体比例以报价单为准。</p></div><div class="payment-grid"><article class="payment-card"><span>30%</span><h3>立项阶段</h3><p>确认需求范围、排期和合作后支付。</p></article><article class="payment-card"><span>40%</span><h3>阶段交付</h3><p>核心模块完成并通过阶段验收后支付。</p></article><article class="payment-card"><span>30%</span><h3>最终验收</h3><p>完成最终验收、部署和资料交接后支付。</p></article><article class="payment-card support-card"><span>售后支持</span><h3>维护与新需求</h3><p>按报价单与合同约定执行，区分问题修复、小幅优化和新增功能。</p></article></div></div></section>

    <section class="section" aria-labelledby="pricing-faq-title"><div class="wrap"><div class="section-head"><h2 id="pricing-faq-title" class="section-title">报价说明常见问题</h2><p class="section-subtitle">以下内容用于说明常见合作口径，最终以确认的报价单与合同为准。</p></div><div class="faq-grid"><article class="faq-card"><h3>报价会根据哪些因素确定？</h3><p>平台数量、功能模块、流程复杂度、接口与数据迁移、交付要求都会影响报价。</p></article><article class="faq-card"><h3>可以先做首期核心版本吗？</h3><p>可以。建议先定义首期完整业务流程，并为后续模块预留接口和数据结构。</p></article><article class="faq-card"><h3>需求中途变化怎么办？</h3><p>先记录变更影响，再确认新的费用、排期和验收范围。</p></article><article class="faq-card"><h3>上线后的维护怎么计算？</h3><p>按报价单与合同约定执行，问题修复、小幅优化和新增功能分别评估。</p></article><article class="faq-card"><h3>是否包含源代码和部署资料？</h3><p>根据报价和合同约定交付，报价确认时会明确源代码、设计稿、账号和部署资料的归属与交接范围。</p></article><article class="faq-card"><h3>第三方费用由谁承担？</h3><p>服务器、域名、短信、支付、地图和应用市场等平台费用由项目方承担；如需代办，按实际费用结算。</p></article></div></div></section>

    <section class="contact-section" id="contact"><div class="wrap"><div class="contact-panel"><div><h2>把业务类型、核心功能和上线目标发来，我先帮你确认报价范围。</h2><p>建议同时提供需要的端、参考系统、第三方接口和预计上线时间。</p><div class="pricing-contact-chips" aria-label="报价前准备信息"><span>业务类型</span><span>核心功能</span><span>需要的端</span><span>预计上线时间</span></div></div><RouterLink class="btn dark" to="/contact">提交需求信息</RouterLink></div></div></section>
    <SiteFooter text="小肥羊开发工作室 · 报价说明" />
  </main>
</template>

<script setup>
import SiteNav from '../components/SiteNav.vue'
import SiteFooter from '../components/SiteFooter.vue'
</script>
