<template>
  <main class="site content-page" id="site" tabindex="-1">
    <div class="wrap"><SiteNav /><section class="content-hero" aria-labelledby="process-title"><div><div class="eyebrow">合作流程 · 交付物 · 验收</div><h1 id="process-title">从需求到上线，分阶段把项目推进清楚。</h1><p class="content-lead">流程页的重点不是展示“我会开发”，而是让客户知道什么时候需要提供资料、什么时候确认结果、需求变化如何处理。</p><div class="hero-actions"><RouterLink class="btn primary" to="/pricing">查看报价说明</RouterLink><RouterLink class="btn secondary" to="/contact">预约流程评估</RouterLink></div></div><div class="hero-summary"><span>流程原则</span><strong>先范围 · 再排期 · 分阶段验收</strong><p>【待补充：标准项目周期】</p><div class="summary-line"><b>客户确认</b><span>需求、原型、阶段版本、验收</span></div><div class="summary-line"><b>开发交付</b><span>文档、代码、环境和上线资料</span></div></div></section></div>

    <section class="section" aria-labelledby="stage-title"><div class="wrap"><div class="section-head"><h2 id="stage-title" class="section-title">六个交付阶段</h2><p class="section-subtitle">每个阶段的具体时长需要根据项目范围确认，以下先保留结构。</p></div><div class="delivery-stage-grid"><article class="delivery-stage"><span>01</span><h3>需求沟通与范围评估</h3><p>输入：业务目标、用户角色、参考系统和现有资料。</p><strong>输出：功能清单、首期边界、初步排期。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article><article class="delivery-stage"><span>02</span><h3>页面原型与流程确认</h3><p>输入：已确认的业务范围和核心链路。</p><strong>输出：页面结构、流程图、字段和状态。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article><article class="delivery-stage"><span>03</span><h3>视觉与技术方案</h3><p>输入：原型、品牌资料和平台要求。</p><strong>输出：视觉规范、技术选型、数据和接口方案。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article><article class="delivery-stage"><span>04</span><h3>前后端开发与联调</h3><p>输入：确认后的原型、视觉和技术方案。</p><strong>输出：阶段版本、接口联调记录和开发文档。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article><article class="delivery-stage"><span>05</span><h3>测试验收与问题修复</h3><p>输入：阶段版本、验收清单和测试账号。</p><strong>输出：问题记录、修复版本、验收结论。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article><article class="delivery-stage"><span>06</span><h3>部署上线与资料交接</h3><p>输入：上线账号、域名、证书和发布资质。</p><strong>输出：生产版本、部署说明、账号和维护建议。</strong><small>周期：`【待补充：时长】` · 确认人：`【待补充】`</small></article></div></div></section>

    <section class="section soft-section" aria-labelledby="responsibility-title"><div class="wrap"><div class="section-head"><h2 id="responsibility-title" class="section-title">谁确认、谁交付，要在合作前说清楚</h2></div><div class="split-grid"><article class="info-panel"><div class="eyebrow">客户需要准备</div><ul class="check-list"><li>业务规则、价格、商品 / 服务资料和现有数据。</li><li>第三方平台账号、支付资质、域名和发布权限。</li><li>项目决策人、测试负责人和最终验收人。</li><li>每个阶段在【待补充：确认时限】内反馈。</li></ul></article><article class="info-panel"><div class="eyebrow">开发者负责</div><ul class="check-list"><li>将需求拆成页面、流程、字段、权限和验收项。</li><li>按阶段提供演示版本、问题记录和交付资料。</li><li>协助部署、发布、账号交接和上线初期排查。</li><li>记录未完成项和后续迭代建议。</li></ul></article></div></div></section>

    <section class="section" aria-labelledby="rules-title"><div class="wrap"><div class="section-head"><h2 id="rules-title" class="section-title">需求变更、验收和延期规则</h2><p class="section-subtitle">以下是需要在报价或合同中落地的字段，当前仅作提醒。</p></div><div class="rule-grid"><article class="rule-card"><h3>需求变更</h3><p>小范围文案或样式优化可在阶段内调整；涉及流程、数据结构、端数量或第三方能力的变化，需要重新评估。</p><span>【待补充：变更计费方式】</span></article><article class="rule-card"><h3>阶段验收</h3><p>以确认的功能清单和验收标准为准，客户在约定时间内集中反馈，避免反复零散修改。</p><span>【待补充：验收反馈时限】</span></article><article class="rule-card"><h3>项目延期</h3><p>客户资料、账号或确认延迟会影响排期，需记录原因和新的预计时间。</p><span>【待补充：延期处理方式】</span></article><article class="rule-card"><h3>上线维护</h3><p>区分上线问题修复与新需求开发，分别记录优先级、响应方式和费用。</p><span>【待补充：售后期限 / SLA】</span></article></div></div></section>

    <section class="contact-section" id="contact"><div class="wrap"><div class="contact-panel"><div><h2>想先确认合作节奏，可以把项目范围发来。</h2><p>我会按阶段说明需要准备的资料、交付物和确认节点。</p></div><RouterLink class="btn dark" to="/contact">预约流程沟通</RouterLink></div></div></section>
    <SiteFooter text="小肥羊开发工作室 · 合作流程" />
  </main>
</template>

<script setup>
import SiteNav from '../components/SiteNav.vue'
import SiteFooter from '../components/SiteFooter.vue'
</script>
