<template>
  <main class="site content-page process-page" id="site" tabindex="-1">
    <div class="wrap"><SiteNav /><section class="content-hero" aria-labelledby="process-title"><div><div class="eyebrow">合作流程 · 阶段成果 · 上线确认</div><h1 id="process-title">从需求到上线，每一步都有明确成果。</h1><p class="content-lead">从需求评估、原型设计到开发、验收和上线，每个阶段都明确需要准备什么、会产出什么，以及由谁确认。</p><div class="hero-actions"><RouterLink class="btn primary" to="/pricing">查看报价说明</RouterLink><RouterLink class="btn secondary" to="/contact">预约流程评估</RouterLink></div></div><div class="hero-summary"><span>流程原则</span><strong>先范围 · 再排期 · 分阶段确认</strong><p>周期会根据项目范围和资料确认节奏确定。</p><div class="summary-line"><b>客户确认</b><span>范围、原型、阶段版本、验收结果</span></div><div class="summary-line"><b>开发交付</b><span>方案、版本、文档、环境和上线资料</span></div></div></section></div>

    <section class="section" id="delivery-stages" aria-labelledby="stage-title"><div class="wrap"><div class="section-head"><h2 id="stage-title" class="section-title">六个交付阶段</h2><p class="section-subtitle">每个阶段都有需要准备的资料、阶段成果和确认节点，完成前一阶段确认后再进入下一阶段。</p></div><div class="process-phase-row" aria-label="合作阶段分组"><span>01–02 · 评估与设计</span><span>03–04 · 方案与开发</span><span>05–06 · 验收与上线</span></div><div class="delivery-stage-grid"><article class="delivery-stage"><span>01</span><h3>需求沟通与范围评估</h3><p>需要准备：业务目标、用户角色、参考系统和现有资料。</p><strong>阶段成果：功能清单、首期边界、初步排期。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article><article class="delivery-stage"><span>02</span><h3>页面原型与流程确认</h3><p>需要准备：已确认的业务范围和完整业务流程。</p><strong>阶段成果：页面结构、流程图、字段和状态。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article><article class="delivery-stage"><span>03</span><h3>视觉与技术方案</h3><p>需要准备：原型、品牌资料和平台要求。</p><strong>阶段成果：视觉规范、技术选型、数据和接口方案。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article><article class="delivery-stage"><span>04</span><h3>前后端开发与接口测试</h3><p>需要准备：确认后的原型、视觉和技术方案。</p><strong>阶段成果：阶段版本、接口测试记录和开发文档。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article><article class="delivery-stage"><span>05</span><h3>测试验收与问题修复</h3><p>需要准备：阶段版本、验收清单和测试账号。</p><strong>阶段成果：问题记录、修复版本、验收结论。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article><article class="delivery-stage"><span>06</span><h3>部署上线与资料交接</h3><p>需要准备：上线账号、域名、证书和发布资质。</p><strong>阶段成果：生产版本、部署说明、账号和维护建议。</strong><small>周期：按项目范围排期 · 确认：客户指定负责人</small></article></div></div></section>

    <section class="section soft-section" id="responsibilities" aria-labelledby="responsibility-title"><div class="wrap"><div class="section-head"><h2 id="responsibility-title" class="section-title">合作双方的准备与交付责任</h2></div><div class="split-grid"><article class="info-panel"><div class="eyebrow">客户需要准备</div><ul class="check-list"><li>业务规则、价格、商品 / 服务资料和现有数据。</li><li>第三方平台账号、支付资质、域名和发布权限。</li><li>项目决策人、测试负责人和最终验收人。</li><li>按约定时间集中反馈，避免零散修改影响排期。</li></ul></article><article class="info-panel"><div class="eyebrow">开发者负责</div><ul class="check-list"><li>将需求拆成页面、流程、字段、权限和验收项。</li><li>按阶段提供演示版本、问题记录和交付资料。</li><li>协助部署、发布、账号交接和上线初期排查。</li><li>记录未完成项和后续迭代建议。</li></ul></article></div></div></section>

    <section class="section" id="rules" aria-labelledby="rules-title"><div class="wrap"><div class="section-head"><h2 id="rules-title" class="section-title">需求变更、验收和延期规则</h2><p class="section-subtitle">提前约定变更、验收、延期和维护规则，减少后续沟通成本。</p></div><div class="rule-grid"><article class="rule-card"><h3>需求变更</h3><p>小范围文案或样式优化可在阶段内调整；涉及流程、数据结构、平台数量或第三方能力的变化，需要重新评估。</p><span>按变更影响评估费用与排期</span></article><article class="rule-card"><h3>阶段验收</h3><p>以确认的功能清单和验收标准为准，客户在约定时间内集中反馈，避免反复零散修改。</p><span>约定时间内集中反馈并确认结论</span></article><article class="rule-card"><h3>项目延期</h3><p>客户资料、账号或确认延迟会影响排期，需记录原因和新的预计时间。</p><span>排期相应顺延并记录原因</span></article><article class="rule-card"><h3>上线维护</h3><p>区分上线问题修复与新需求开发，分别记录优先级、响应方式和费用。</p><span>维护期限、响应方式和费用按报价与合同约定</span></article></div></div></section>

    <section class="contact-section" id="contact"><div class="wrap"><div class="contact-panel"><div><h2>想先确认合作节奏，可以把项目范围发来。</h2><p>准备业务类型、主要功能、参考系统和预计上线时间，我会按阶段说明资料、阶段成果和确认节点。</p><div class="chip-row"><span class="chip">业务类型</span><span class="chip">主要功能</span><span class="chip">参考系统</span><span class="chip">上线时间</span></div></div><RouterLink class="btn dark" to="/contact">预约流程沟通</RouterLink></div></div></section>
    <SiteFooter text="小肥羊开发工作室 · 合作流程" />
  </main>
</template>

<script setup>
import SiteNav from '../components/SiteNav.vue'
import SiteFooter from '../components/SiteFooter.vue'
</script>
